// `npm run data`: looks up each demo song's cover on Spotify's public oEmbed (no login, no Web API)
// and rewrites src/data/tracks.ts. Run it when a cover URL stops loading; the page falls back to a
// coloured disc if one does. The seed below is the only hand-edited part.
import { writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

// `match` must appear in Spotify's own title for the id, so a wrong id fails loudly.
// Durations are in seconds, read off Spotify's track pages; they only drive the scripted progress bar.
const SEED = [
  { id: '6Yj7Zhxt73uvwFFvzQXdxO', match: "Flight's Booked", artist: 'Drake', album: 'Honestly, Nevermind', duration: 254 },
  { id: '2aSC2xhRxOLiiZZVjhbylH', match: "Hold On, We're Going Home", artist: 'Drake, Majid Jordan', album: 'Nothing Was the Same', duration: 227 },
  { id: '09nb96uzHeopbhbcYZBAWe', match: 'True', artist: 'Spandau Ballet', album: 'True', duration: 393 },
  { id: '21jGcNKet2qwijlDFuPiPb', match: 'Circles', artist: 'Post Malone', album: "Hollywood's Bleeding", duration: 215 },
];

const out = join(dirname(fileURLToPath(import.meta.url)), '../src/data/tracks.ts');
const tracks = [];
for (const s of SEED) {
  const url = `https://open.spotify.com/oembed?url=${encodeURIComponent(`https://open.spotify.com/track/${s.id}`)}`;
  const res = await fetch(url);
  if (!res.ok) throw new Error(`oEmbed ${res.status} for ${s.id}`);
  const j = await res.json();
  if (!j.title.includes(s.match)) throw new Error(`id ${s.id} is "${j.title}", expected a title with "${s.match}"`);
  if (!/^https:\/\/[^/]+\/image\//.test(j.thumbnail_url)) throw new Error(`unexpected cover url for ${s.id}: ${j.thumbnail_url}`);
  tracks.push({ id: s.id, title: j.title, artist: s.artist, album: s.album, duration: s.duration, cover: j.thumbnail_url });
  console.log(`ok  ${s.id}  ${j.title}  (${s.artist})`);
}

writeFileSync(out, `// Generated by tools/resolve-covers.mjs (npm run data). Do not edit by hand; edit the seed there.
export interface Track { id: string; title: string; artist: string; album: string; duration: number; cover: string }

export const tracks: Track[] = ${JSON.stringify(tracks, null, 2)};
`);
console.log(`wrote ${out}`);
