// `npm run data`: looks up each demo song's cover on Spotify's public oEmbed (no login, no Web API)
// and rewrites src/data/tracks.ts. Run it when a cover URL stops loading; the page falls back to a
// coloured disc if one does. The seed below is the only hand-edited part.
//
// It also works out each cover's accent here, offline, with the app's own rule (src/notch/accent.ts):
// the covers are cross-origin, so the page itself cannot read their pixels. macOS only (`sips`).
// `node tools/resolve-covers.mjs --accent <image url>` prints one cover's accent and exits.
import { writeFileSync, readFileSync, mkdtempSync, rmSync } from 'node:fs';
import { execFileSync } from 'node:child_process';
import { tmpdir } from 'node:os';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';
import { accentOf, toHex, SAMPLE } from '../src/notch/accent.ts';

/** The cover shrunk to 24x24 by `sips`, as RGBA bytes, then the app's accent rule. */
async function accent(url) {
  const res = await fetch(url);
  if (!res.ok) throw new Error(`cover ${res.status}: ${url}`);
  const dir = mkdtempSync(join(tmpdir(), 'cover-'));
  try {
    writeFileSync(join(dir, 'c.jpg'), Buffer.from(await res.arrayBuffer()));
    execFileSync('sips', ['-z', String(SAMPLE), String(SAMPLE), '-s', 'format', 'bmp', join(dir, 'c.jpg'), '--out', join(dir, 'c.bmp')], { stdio: 'ignore' });
    const bmp = readFileSync(join(dir, 'c.bmp'));
    const offset = bmp.readUInt32LE(10), w = bmp.readInt32LE(18), h = bmp.readInt32LE(22), bpp = bmp.readUInt16LE(28);
    if (w !== SAMPLE || Math.abs(h) !== SAMPLE || bpp !== 24) throw new Error(`unexpected bmp ${w}x${h}x${bpp}`);
    const row = Math.ceil((w * 3) / 4) * 4, rgba = [];
    for (let y = 0; y < SAMPLE; y++) for (let x = 0; x < SAMPLE; x++) {
      const i = offset + y * row + x * 3; // BGR; row order does not matter to a colour count
      rgba.push(bmp[i + 2], bmp[i + 1], bmp[i], 255);
    }
    const c = accentOf(rgba);
    return c ? toHex(c) : null;
  } finally { rmSync(dir, { recursive: true, force: true }); }
}

if (process.argv[2] === '--accent') { console.log(await accent(process.argv[3])); process.exit(0); }

// `match` must appear in Spotify's own title for the id, so a wrong id fails loudly.
// Durations are in seconds, from Spotify search snippets (not verified); they only drive the scripted
// progress bar. bpm is a rough tempo that only sets the waveform's beat.
const SEED = [
  { id: '6Yj7Zhxt73uvwFFvzQXdxO', match: "Flight's Booked", artist: 'Drake', album: 'Honestly, Nevermind', duration: 254, bpm: 122 },
  { id: '2aSC2xhRxOLiiZZVjhbylH', match: "Hold On, We're Going Home", artist: 'Drake, Majid Jordan', album: 'Nothing Was the Same', duration: 227, bpm: 100 },
  { id: '09nb96uzHeopbhbcYZBAWe', match: 'True', artist: 'Spandau Ballet', album: 'True', duration: 393, bpm: 98 },
  { id: '21jGcNKet2qwijlDFuPiPb', match: 'Circles', artist: 'Post Malone', album: "Hollywood's Bleeding", duration: 215, bpm: 120 },
];

const out = join(dirname(fileURLToPath(import.meta.url)), '../src/data/tracks.ts');
const tracks = [];
for (const s of SEED) {
  const url = `https://open.spotify.com/oembed?url=${encodeURIComponent(`https://open.spotify.com/track/${s.id}`)}`;
  const res = await fetch(url);
  if (!res.ok) throw new Error(`oEmbed ${res.status} for ${s.id}`);
  const j = await res.json();
  if (!j.title.includes(s.match)) throw new Error(`id ${s.id} is "${j.title}", expected a title with "${s.match}"`);
  if (!/^https:\/\/[^/]+\/image\//.test(j.thumbnail_url)) throw new Error(`unexpected cover url for ${s.id}: ${j.thumbnail_url}`);
  const tint = await accent(j.thumbnail_url);
  tracks.push({ id: s.id, title: j.title, artist: s.artist, album: s.album, duration: s.duration, bpm: s.bpm, cover: j.thumbnail_url, tint });
  console.log(`ok  ${s.id}  ${j.title}  (${s.artist})  accent ${tint ?? 'none (grey cover: white)'}`);
}

writeFileSync(out, `// Generated by tools/resolve-covers.mjs (npm run data). Do not edit by hand; edit the seed there.
// tint: the cover's accent (app rule), or null for a grey cover, which leaves the line white.
export interface Track { id: string; title: string; artist: string; album: string; duration: number; bpm: number; cover: string; tint: string | null }

export const tracks: Track[] = ${JSON.stringify(tracks, null, 2)};
`);
console.log(`wrote ${out}`);
