// Generated by tools/resolve-covers.mjs (npm run data). Do not edit by hand; edit the seed there.
export interface Track { id: string; title: string; artist: string; album: string; duration: number; cover: string }

export const tracks: Track[] = [
  {
    "id": "6Yj7Zhxt73uvwFFvzQXdxO",
    "title": "Flight's Booked",
    "artist": "Drake",
    "album": "Honestly, Nevermind",
    "duration": 254,
    "cover": "https://image-cdn-fa.spotifycdn.com/image/ab67616d00001e028dc0d801766a5aa6a33cbe37"
  },
  {
    "id": "2aSC2xhRxOLiiZZVjhbylH",
    "title": "Hold On, We're Going Home",
    "artist": "Drake, Majid Jordan",
    "album": "Nothing Was the Same",
    "duration": 227,
    "cover": "https://image-cdn-fa.spotifycdn.com/image/ab67616d00001e02a90d170c61fb7d063d47161d"
  },
  {
    "id": "09nb96uzHeopbhbcYZBAWe",
    "title": "True - 2003 - Remaster",
    "artist": "Spandau Ballet",
    "album": "True",
    "duration": 393,
    "cover": "https://image-cdn-fa.spotifycdn.com/image/ab67616d00001e024dfe95bf476557d1dc381fec"
  },
  {
    "id": "21jGcNKet2qwijlDFuPiPb",
    "title": "Circles",
    "artist": "Post Malone",
    "album": "Hollywood's Bleeding",
    "duration": 215,
    "cover": "https://image-cdn-ak.spotifycdn.com/image/ab67616d00001e029478c87599550dd73bfa7e02"
  }
];
